### ISSUE TITLE
numpy not found

### ISSUE THREAD

**Issue by errotu** [anishathalye/neural-hash-collider#2]
Thank you for this interesting demonstration!

When I tried it on Ubuntu 21.04, I received the following error:

> Traceback (most recent call last):
>   File "collide.py", line 3, in <module>
>     import numpy as np
> ImportError: No module named numpy

It worked like a charm when I used "python3" instead of simply "python" as command. Maybe that's an interesting advice for the readme.

**Comment by anishathalye** [comment]
I think this has to do with your particular Python environment setup. There are many ways people set up Python envs: virtualenv, conda, ..., so I'd prefer not to add instructions related to this in the readme.
