### ISSUE TITLE
[Question] Onnx -> TF

### ISSUE THREAD

**Issue by IaroslavElistratov** [anishathalye/neural-hash-collider#6]
Could you please clarify what is the reason for using `tf.compat.v1.Session()` instead of TF 2 eager execution? Is it related to computing the gradient for the model converted from onnx?

**Comment by anishathalye** [comment]
Yes, I vaguely recall that this was the easiest way for me to get gradients through the ONNX model. I don't remember if eager mode wasn't supported, or if I just got this version working first and moved on.
